//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotatePicClient.RotatePicService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RotatePicService.IRotatePicService")]
    public interface IRotatePicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRotatePicService/RotatePic", ReplyAction="http://tempuri.org/IRotatePicService/RotatePicResponse")]
        void RotatePic(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRotatePicService/RotatePic", ReplyAction="http://tempuri.org/IRotatePicService/RotatePicResponse")]
        System.Threading.Tasks.Task RotatePicAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRotatePicService/StartRotatePic", ReplyAction="http://tempuri.org/IRotatePicService/StartRotatePicResponse")]
        void StartRotatePic(string path, int angle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRotatePicService/StartRotatePic", ReplyAction="http://tempuri.org/IRotatePicService/StartRotatePicResponse")]
        System.Threading.Tasks.Task StartRotatePicAsync(string path, int angle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRotatePicServiceChannel : RotatePicClient.RotatePicService.IRotatePicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RotatePicServiceClient : System.ServiceModel.ClientBase<RotatePicClient.RotatePicService.IRotatePicService>, RotatePicClient.RotatePicService.IRotatePicService {
        
        public RotatePicServiceClient() {
        }
        
        public RotatePicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RotatePicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RotatePicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RotatePicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RotatePic(int i) {
            base.Channel.RotatePic(i);
        }
        
        public System.Threading.Tasks.Task RotatePicAsync(int i) {
            return base.Channel.RotatePicAsync(i);
        }
        
        public void StartRotatePic(string path, int angle) {
            base.Channel.StartRotatePic(path, angle);
        }
        
        public System.Threading.Tasks.Task StartRotatePicAsync(string path, int angle) {
            return base.Channel.StartRotatePicAsync(path, angle);
        }
    }
}
